[build]
  command = "node netlify-build-debug.js"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Add redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 